### ISSUE TITLE
Try not repeating code

### ISSUE THREAD

**Issue by maurhub** [gcastellini/postgresql-challenge#1]
@gcastellini do you think we can improve the SQL code a bit? 

For example here, https://github.com/gcastellini/postgresql-challenge/blob/f7518887e99369110ac46e4dd376d6a941fa4669/script.sql#L21
You're updating the months, but down below you're doing the same with a code that kind of looks a copy paste. Could you improve this?

**Comment by gcastellini** [comment]
@maurhub I tried to do it all in one statement like this:
![image](https://github.com/gcastellini/postgresql-challenge/assets/98000270/84170312-3de1-40d8-8280-54db6d11fb97)

But I get an error: 
![image](https://github.com/gcastellini/postgresql-challenge/assets/98000270/f784f7e7-5406-4143-bb5d-29597b040498)

**Comment by maurhub** [comment]
What I mean is if you might find a way to alter both woman government employment table and the merged table with the functions. Because you're setting the month in the same way for both tables

**Comment by gcastellini** [comment]
@maurhub yes, it occurs to me now that I could have created a table with the definition for each period, and then performed a LEFT join to both tables.
