### ISSUE TITLE
Possible division by zero

### ISSUE THREAD

**Issue by maurhub** [gcastellini/postgresql-challenge#3]
Could you elaborate on what might happen at this line? and how to fix it

https://github.com/gcastellini/postgresql-challenge/blob/f7518887e99369110ac46e4dd376d6a941fa4669/script.sql#LL117C48-L117C56

**Comment by gcastellini** [comment]
@maurhub I added NULLIF to divisor 
![image](https://github.com/gcastellini/postgresql-challenge/assets/98000270/c9c5ff96-e10e-4e9e-aca7-9ffa6146c04f)

**Comment by maurhub** [comment]
But it is ok to divide by NULL? What would be the result?

**Comment by gcastellini** [comment]
@maurhub if you divide by NULL in SQL, you get NULL as the result. In this case, if we do not want NULL to show up in the API we can use the CASE statement to convert the value to zero (or other value) in case the divisor is zero:

![image](https://github.com/gcastellini/postgresql-challenge/assets/98000270/b47b1bac-f26d-4f6b-8cb1-206eaa5daac8)
